all:
	gcc BiBakBOXServer.c -pthread -Wall -pedantic-errors -g -o BiBakBOXServer
	gcc BiBakBOXClient.c -pthread -Wall -pedantic-errors -g -o BiBakBOXClient

clean:
	rm -f *.o BiBakBOXClient BiBakBOXServer *.log

